apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tink-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tink-server-role
subjects:
  - kind: ServiceAccount
    name: tink-server
    namespace: tink-system