apiVersion: apps/v1
kind: Deployment
metadata:
  name: tink-controller
spec:
  replicas: 1
  selector: { }
  template:
    spec:
      containers:
        - image: quay.io/tinkerbell/tink-controller:v0.8.0
          imagePullPolicy: IfNotPresent
          name: tink-controller
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: tink-controller