apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - role.yaml
  - rolebinding.yaml
  - service-account.yaml
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: tink-controller