apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rufio-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rufio-manager-role
subjects:
  - kind: ServiceAccount
    name: rufio-controller-manager
    namespace: tink-system