apiVersion: apps/v1
kind: Deployment
metadata:
  name: rufio
spec:
  selector: { }
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: quay.io/tinkerbell/rufio:v0.1.0
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --leader-elect
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: rufio-controller-manager
      terminationGracePeriodSeconds: 10