apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rufio-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rufio-leader-election-role
subjects:
  - kind: ServiceAccount
    name: rufio-controller-manager
    namespace: tink-system