apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hegel-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hegel-role
subjects:
  - kind: ServiceAccount
    name: hegel
    namespace: tink-system