apiVersion: v1
kind: Service
metadata:
  name: tink-stack
spec:
  type: LoadBalancer
  loadBalancerClass: kube-vip.io/kube-vip-class
  loadBalancerIP: 192.168.2.112
  externalTrafficPolicy: Local
  ports:
    - name: hegel
      port: 50061
      protocol: TCP
    - name: tink-server
      port: 42113
      protocol: TCP
    - name: hook-files
      port: 8080
      protocol: TCP
  selector: { }